package DataBase;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by Bryan on 1/7/2017.
 */

public class DBHelper extends SQLiteOpenHelper {

    private static final String DB_NAME = "eecc";
    private static final int DB_SCHEME_VERSION = 1;

    public DBHelper(Context context) {
        super(context, DB_NAME, null, DB_SCHEME_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(DataBaseManager.CREATE_TABLE_CANTONS);
        db.execSQL(DataBaseManager.CREATE_TABLE_CORROSIONDAMAGEINDEXES);
        db.execSQL(DataBaseManager.CREATE_TABLE_COUNTRIES);
        db.execSQL(DataBaseManager.CREATE_TABLE_DISTRICTS);
        db.execSQL(DataBaseManager.CREATE_TABLE_ES);
        db.execSQL(DataBaseManager.CREATE_TABLE_ESINFORMATION);
        db.execSQL(DataBaseManager.CREATE_TABLE_EVALUATIONS);
        db.execSQL(DataBaseManager.CREATE_TABLE_IAAINFORMATION);
        db.execSQL(DataBaseManager.CREATE_TABLE_IAL);
        db.execSQL(DataBaseManager.CREATE_TABLE_IALINFORMATION);
        db.execSQL(DataBaseManager.CREATE_TABLE_IAT);
        db.execSQL(DataBaseManager.CREATE_TABLE_IATINFORMATION);
        db.execSQL(DataBaseManager.CREATE_TABLE_IDCINDICATORS);
        db.execSQL(DataBaseManager.CREATE_TABLE_IDE);
        db.execSQL(DataBaseManager.CREATE_TABLE_IDEINFORMATION);
        db.execSQL(DataBaseManager.CREATE_TABLE_INDICATORNAMES);
        db.execSQL(DataBaseManager.CREATE_TABLE_PROJECTS);
        db.execSQL(DataBaseManager.CREATE_TABLE_PROVINCES);
        db.execSQL(DataBaseManager.CREATE_TABLE_STRUCTURALDAMAGEINDEXES);
        db.execSQL(DataBaseManager.CREATE_TABLE_STRUCTURALINDEXES);
        db.execSQL(DataBaseManager.CREATE_TABLE_STRUCTURETYPES);
        db.execSQL(DataBaseManager.CREATE_TABLE_TOKENS);
        db.execSQL(DataBaseManager.CREATE_TABLE_USERS);
        db.execSQL(DataBaseManager.CREATE_TABLE_CONTACTO);
        db.execSQL(DataBaseManager.CREATE_TABLE_USUARIO);
        db.execSQL("INSERT INTO android_metadata (locale) VALUES ('en_US');");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (101, 'San José', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (102, 'Escazú', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (103, 'Desamparados', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (104, 'Puriscal', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (105, 'Tarrazú', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (106, 'Aserrí', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (107, 'Mora', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (108, 'Goicoechea', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (109, 'Santa Ana', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (110, 'Alajuelita', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (111, 'Vázquez de Coronado', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (112, 'Acosta', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (113, 'Tibás', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (114, 'Moravia', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (115, 'Montes de Oca', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (116, 'Turrubares', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (117, 'Dota', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (118, 'Curridabat', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (119, 'Pérez Zeledón', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (120, 'León Cortés Castro', 1);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (201, 'Alajuela', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (202, 'San Ramón', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (203, 'Grecia', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (204, 'San Mateo', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (205, 'Atenas', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (206, 'Naranjo', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (207, 'Palmares', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (208, 'Poás', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (209, 'Orotina', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (210, 'San Carlos', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (211, 'Zarcero', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (212, 'Valverde Vega', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (213, 'Upala', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (214, 'Los Chiles', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (215, 'Guatuso', 2);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (301, 'Cartago', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (302, 'Paraíso', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (303, 'La Unión', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (304, 'Jiménez', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (305, 'Turrialba', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (306, 'Alvarado', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (307, 'Oreamuno', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (308, 'El Guarco', 3);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (401, 'Heredia', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (402, 'Barva', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (403, 'Santo Domingo', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (404, 'Santa Bárbara', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (405, 'San Rafael', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (406, 'San Isidro', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (407, 'Belén', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (408, 'Flores', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (409, 'San Pablo', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (410, 'Sarapiquí', 4);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (501, 'Liberia', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (502, 'Nicoya', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (503, 'Santa Cruz', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (504, 'Bagaces', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (505, 'Carrillo', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (506, 'Cañas', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (507, 'Abangares', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (508, 'Tilarán', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (509, 'Nandayure', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (510, 'La Cruz', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (511, 'Hojancha', 5);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (601, 'Puntarenas', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (602, 'Esparza', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (603, 'Buenos Aires', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (604, 'Montes de Oro', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (605, 'Osa', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (606, 'Quepos', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (607, 'Golfito', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (608, 'Coto Brus', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (609, 'Parrita', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (610, 'Corredores', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (611, 'Garabito', 6);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (701, 'Limón', 7);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (702, 'Pococí', 7);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (703, 'Siquirres', 7);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (704, 'Talamanca', 7);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (705, 'Matina', 7);");
        db.execSQL("INSERT INTO Cantons (CantonId, CantonName, ProvinceId) VALUES (706, 'Guácimo', 7);");
        db.execSQL("INSERT INTO Countries (CountryId, CountryName) VALUES (1, 'Costa Rica');");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10101, 'Carmen', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10102, 'Merced', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10103, 'Hospital', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10104, 'Catedral', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10105, 'Zapote', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10106, 'San Francisco de Dos Ríos', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10107, 'Uruca', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10108, 'Mata Redonda', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10109, 'Pavas', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10110, 'Hatillo', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10111, 'San Sebastián', 101);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10201, 'Escazú', 102);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10202, 'San Antonio', 102);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10203, 'San Rafael', 102);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10301, 'Desamparados', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10302, 'San Miguel', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10303, 'San Juan de Dios', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10304, 'San Rafael Arriba', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10305, 'San Antonio', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10306, 'Frailes', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10307, 'Patarrá', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10308, 'San Cristóbal', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10309, 'Rosario', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10310, 'Damas', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10311, 'San Rafael Abajo', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10312, 'Gravilias', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10313, 'Los Guido', 103);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10401, 'Santiago', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10402, 'Mercedes Sur', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10403, 'Barbacoas', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10404, 'Grifo Alto', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10405, 'San Rafael', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10406, 'Candelarita', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10407, 'Desamparaditos', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10408, 'San Antonio', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10409, 'Chires', 104);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10501, 'San Marcos', 105);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10502, 'San Lorenzo', 105);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10503, 'San Carlos', 105);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10601, 'Aserrí', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10602, 'Tarbaca', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10603, 'Vuelta de Jorco', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10604, 'San Gabriel', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10605, 'Legua', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10606, 'Monterrey', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10607, 'Salitrillos', 106);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10701, 'Colón', 107);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10702, 'Guayabo', 107);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10703, 'Tabarcia', 107);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10704, 'Piedras Negras', 107);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10705, 'Picagres', 107);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10706, 'Jaris', 107);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10801, 'Guadalupe', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10802, 'San Francisco', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10803, 'Calle Blancos', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10804, 'Mata de Plátano', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10805, 'Ipís', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10806, 'Rancho Redondo', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10807, 'Purral', 108);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10901, 'Santa Ana', 109);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10902, 'Salitral', 109);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10903, 'Pozos', 109);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10904, 'Uruca', 109);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10905, 'Piedades', 109);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (10906, 'Brasil', 109);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11001, 'Alajuelita', 110);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11002, 'San Josecito', 110);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11003, 'San Antonio', 110);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11004, 'Concepción', 110);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11005, 'San Felipe', 110);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11101, 'San Isidro', 111);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11102, 'San Rafael', 111);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11103, 'Dulce Nombre de Jesús', 111);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11104, 'Patalillo', 111);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11105, 'Cascajal', 111);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11201, 'San Ignacio', 112);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11202, 'Guaitil', 112);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11203, 'Palmichal', 112);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11204, 'Cangrejal', 112);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11205, 'Sabanillas', 112);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11301, 'San Juan', 113);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11302, 'Cinco Esquinas', 113);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11303, 'Anselmo Llorente', 113);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11304, 'León XIII', 113);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11305, 'Colima', 113);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11401, 'San Vicente', 114);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11402, 'San Jerónimo', 114);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11403, 'La Trinidad', 114);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11501, 'San Pedro', 115);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11502, 'Sabanilla', 115);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11503, 'Mercedes', 115);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11504, 'San Rafael', 115);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11601, 'San Pablo', 116);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11602, 'San Pedro', 116);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11603, 'San Juan de Mata', 116);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11604, 'San Luis', 116);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11605, 'Carara', 116);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11701, 'Santa María', 117);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11702, 'Jardín', 117);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11703, 'Copey', 117);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11801, 'Curridabat', 118);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11802, 'Granadilla', 118);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11803, 'Sánchez', 118);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11804, 'Tirrases', 118);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11901, 'San Isidro de El General', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11902, 'General', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11903, 'Daniel Flores', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11904, 'Rivas', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11905, 'San Pedro', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11906, 'Platanares', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11907, 'Pejibaye', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11908, 'Cajón', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11909, 'Barú', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11910, 'Río Nuevo', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (11911, 'Páramo', 119);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (12001, 'San Pablo', 120);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (12002, 'San Andrés', 120);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (12003, 'Llano Bonito', 120);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (12004, 'San Isidro', 120);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (12005, 'Santa Cruz', 120);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (12006, 'San Antonio', 120);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20101, 'Alajuela', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20102, 'San José', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20103, 'Carrizal', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20104, 'San Antonio', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20105, 'Guácima', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20106, 'San Isidro', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20107, 'Sabanilla', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20108, 'San Rafael', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20109, 'Río Segundo', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20110, 'Desamparados', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20111, 'Turrúcares', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20112, 'Tambor', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20113, 'Garita', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20114, 'Sarapiquí', 201);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20201, 'San Ramón', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20202, 'Santiago', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20203, 'San Juan', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20204, 'Piedades Norte', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20205, 'Piedades Sur', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20206, 'San Rafael', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20207, 'San Isidro', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20208, 'Los Ángeles', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20209, 'Alfaro', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20210, 'Volio', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20211, 'Concepción', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20212, 'Zapotal', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20213, 'Peñas Blancas', 202);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20301, 'Grecia', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20302, 'San Isidro', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20303, 'San José', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20304, 'San Roque', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20305, 'Tacares', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20306, 'Río Cuarto', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20307, 'Puente de Piedra', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20308, 'Bolívar', 203);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20401, 'San Mateo', 204);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20402, 'Desmonte', 204);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20403, 'Jesús María', 204);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20501, 'Atenas', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20502, 'Jesús', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20503, 'Mercedes', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20504, 'San Isidro', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20505, 'Concepción', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20506, 'San José', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20507, 'Santa Eulalia', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20508, 'Escobal', 205);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20601, 'Naranjo', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20602, 'San Miguel', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20603, 'San José', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20604, 'Cirrí Sur', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20605, 'San Jerónimo', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20606, 'San Juan', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20607, 'El Rosario', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20608, 'Palmitos', 206);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20701, 'Palmares', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20702, 'Zaragoza', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20703, 'Buenos Aires', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20704, 'Santiago', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20705, 'Candelaria', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20706, 'Esquipulas', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20707, 'La Granja', 207);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20801, 'San Pedro', 208);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20802, 'San Juan', 208);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20803, 'San Rafael', 208);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20804, 'Carrillos', 208);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20805, 'Sabana Redonda', 208);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20901, 'Orotina', 209);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20902, 'El Mastate', 209);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20903, 'Hacienda Vieja', 209);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20904, 'Coyolar', 209);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (20905, 'La Ceiba', 209);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21001, 'Quesada', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21002, 'Florencia', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21003, 'Buenavista', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21004, 'Aguas Zarcas', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21005, 'Venecia', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21006, 'Pital', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21007, 'La Fortuna', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21008, 'La Tigra', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21009, 'La Palmera', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21010, 'Venado', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21011, 'Cutris', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21012, 'Monterrey', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21013, 'Pocosol', 210);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21101, 'Zarcero', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21102, 'Laguna', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21103, 'Tapesco', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21104, 'Guadalupe', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21105, 'Palmira', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21106, 'Zapote', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21107, 'Brisas', 211);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21201, 'Sarchí Norte', 212);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21202, 'Sarchí Sur', 212);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21203, 'Toro Amarillo', 212);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21204, 'San Pedro', 212);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21205, 'Rodríguez', 212);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21301, 'Upala', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21302, 'Aguas Claras', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21303, 'San José (Pizote)', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21304, 'Bijagua', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21305, 'Delicias', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21306, 'Dos Ríos', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21307, 'Yoliyllal', 213);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21401, 'Los Chiles', 214);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21402, 'Caño Negro', 214);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21403, 'El Amparo', 214);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21404, 'San Jorge', 214);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21501, 'San Rafael', 215);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21502, 'Buenavista', 215);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21503, 'Cote', 215);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (21504, 'Katira', 215);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30101, 'Oriental', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30102, 'Occidental', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30103, 'Carmen', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30104, 'San Nicolás', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30105, 'Aguacaliente (San Francisco)', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30106, 'Guadalupe (Arenilla)', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30107, 'Corralillo', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30108, 'Tierra Blanca', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30109, 'Dulce Nombre', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30110, 'Llano Grande', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30111, 'Quebradilla', 301);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30201, 'Paraíso', 302);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30202, 'Santiago', 302);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30203, 'Orosi', 302);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30204, 'Cachí', 302);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30205, 'Llanos de Santa Lucía', 302);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30301, 'Tres Ríos', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30302, 'San Diego', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30303, 'San Juan', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30304, 'San Rafael', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30305, 'Concepción', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30306, 'Dulce Nombre', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30307, 'San Ramón', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30308, 'Río Azul', 303);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30401, 'Juan Viñas', 304);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30402, 'Tucurrique', 304);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30403, 'Pejibaye', 304);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30501, 'Turrialba', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30502, 'La Suiza', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30503, 'Peralta', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30504, 'Santa Cruz', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30505, 'Santa Teresita', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30506, 'Pavones', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30507, 'Tuis', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30508, 'Tayutic', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30509, 'Santa Rosa', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30510, 'Tres Equis', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30511, 'La Isabel', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30512, 'Chirripó', 305);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30601, 'Pacayas', 306);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30602, 'Cervantes', 306);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30603, 'Capellades', 306);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30701, 'San Rafael', 307);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30702, 'Cot', 307);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30703, 'Potrero Cerrado', 307);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30704, 'Cipreses', 307);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30705, 'Santa Rosa', 307);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30801, 'El Tejar', 308);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30802, 'San Isidro', 308);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30803, 'Tobosi', 308);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (30804, 'Patio de Agua', 308);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40101, 'Heredia', 401);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40102, 'Mercedes', 401);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40103, 'San Francisco', 401);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40104, 'Ulloa', 401);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40105, 'Varablanca', 401);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40201, 'Barva', 402);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40202, 'San Pedro', 402);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40203, 'San Pablo', 402);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40204, 'San Roque', 402);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40205, 'Santa Lucía', 402);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40206, 'San José de la Montaña', 402);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40301, 'Santo Domingo', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40302, 'San Vicente', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40303, 'San Miguel', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40304, 'Paracito', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40305, 'Santo Tomás', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40306, 'Santa Rosa', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40307, 'Tures', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40308, 'Para', 403);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40401, 'Santa Bárbara', 404);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40402, 'San Pedro', 404);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40403, 'San Juan', 404);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40404, 'Jesús', 404);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40405, 'Santo Domingo', 404);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40406, 'Puraba', 404);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40501, 'San Rafael', 405);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40502, 'San Josécito', 405);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40503, 'Santiago', 405);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40504, 'Los Ángeles', 405);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40505, 'Concepción', 405);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40601, 'San Isidro', 406);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40602, 'San José', 406);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40603, 'Concepción', 406);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40604, 'San Francisco', 406);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40701, 'San Antonio', 407);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40702, 'La Ribera', 407);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40703, 'La Asunción', 407);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40801, 'San Joaquín de Flores', 408);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40802, 'Barrantes', 408);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40803, 'Llorente', 408);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40901, 'San Pablo', 409);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (40902, 'Rincón de Sabanilla', 409);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (41001, 'Puerto Viejo', 410);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (41002, 'La Virgen', 410);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (41003, 'Horquetas', 410);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (41004, 'Llanuras del Gaspar', 410);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (41005, 'Cureña', 410);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50101, 'Liberia', 501);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50102, 'Cañas Dulces', 501);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50103, 'Mayorga', 501);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50104, 'Nacascolo', 501);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50105, 'Curubande', 501);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50201, 'Nicoya', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50202, 'Mansion', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50203, 'San Antonio', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50204, 'Quebrada Honda', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50205, 'Samara', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50206, 'Nosara', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50207, 'Belén de Nosarita', 502);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50301, 'Santa Cruz', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50302, 'Bolson', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50303, 'Veintisiete de Abril', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50304, 'Tempate', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50305, 'Cartagena', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50306, 'Cuajiniquil', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50307, 'Diria', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50308, 'Cabo Velas', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50309, 'Tamarindo', 503);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50401, 'Bagaces', 504);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50402, 'Fortuna', 504);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50403, 'Mogote', 504);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50404, 'Río Naranjo', 504);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50501, 'Filadelfia', 505);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50502, 'Palmira', 505);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50503, 'Sardinal', 505);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50504, 'Belén', 505);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50601, 'Cañas', 506);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50602, 'Palmira', 506);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50603, 'San Miguel', 506);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50604, 'Bebedero', 506);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50605, 'Porozal', 506);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50701, 'Juntas', 507);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50702, 'Sierra', 507);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50703, 'San Juan', 507);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50704, 'Colorado', 507);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50801, 'Tilarán', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50802, 'Quebrada Grande', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50803, 'Tronadora', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50804, 'Santa Rosa', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50805, 'Líbano', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50806, 'Tierras Morenas', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50807, 'Arenal', 508);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50901, 'Carmona', 509);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50902, 'Santa Rita', 509);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50903, 'Zapotal', 509);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50904, 'San Pablo', 509);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50905, 'Porvenir', 509);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (50906, 'Bejuco', 509);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51001, 'La Cruz', 510);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51002, 'Santa Cecilia', 510);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51003, 'Garita', 510);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51004, 'Santa Elena', 510);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51101, 'Hojancha', 511);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51102, 'Monte Romo', 511);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51103, 'Puerto Carrillo', 511);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (51104, 'Huacas', 511);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60101, 'Puntarenas', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60102, 'Pitahaya', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60103, 'Chomes', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60104, 'Lepanto', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60105, 'Paquera', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60106, 'Manzanillo', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60107, 'Guacimal', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60108, 'Barranca', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60109, 'Monte Verde', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60110, 'Isla del Coco', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60111, 'Cobano', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60112, 'Chacarita', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60113, 'Chira', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60114, 'Acapulco', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60115, 'El Roble', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60116, 'Arancibia', 601);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60201, 'Espiritu Santo', 602);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60202, 'San Juan Grande', 602);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60203, 'Macacona', 602);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60204, 'San Rafael', 602);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60205, 'San Jerónimo', 602);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60301, 'Buenos Aires', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60302, 'Volcan', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60303, 'Potrero Grande', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60304, 'Boruca', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60305, 'Pilas', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60306, 'Colinas', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60307, 'Changena', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60308, 'Briolley', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60309, 'Brunka', 603);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60401, 'Miramar', 604);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60402, 'La Unión', 604);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60403, 'San Isidro', 604);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60501, 'Puerto Cortes', 605);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60502, 'Palmar', 605);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60503, 'Sierpe', 605);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60504, 'Bahia Ballena', 605);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60505, 'Piedras Blancas', 605);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60601, 'Quepos', 606);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60602, 'Savegre', 606);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60603, 'Naranjito', 606);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60701, 'Golfito', 607);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60702, 'Puerto Jiménez', 607);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60703, 'Guaycara', 607);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60704, 'Pavon', 607);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60801, 'San Vito', 608);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60802, 'Sabalito', 608);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60803, 'Aguabuena', 608);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60804, 'Limóncito', 608);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60805, 'Pittier', 608);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (60901, 'Parrita', 609);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (61001, 'Corredor', 610);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (61002, 'La Cuesta', 610);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (61003, 'Canoas', 610);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (61004, 'Laurel', 610);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (61101, 'Jacó', 611);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (61102, 'Tarcoles', 611);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70101, 'Limón', 701);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70102, 'Valle La Estrella', 701);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70103, 'Río Blanco', 701);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70104, 'Matama', 701);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70201, 'Guapiles', 702);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70202, 'Jiménez', 702);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70203, 'Rita', 702);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70204, 'Roxana', 702);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70205, 'Cariari', 702);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70206, 'Colorado', 702);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70301, 'Siquirres', 703);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70302, 'Pacuarito', 703);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70303, 'Florida', 703);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70304, 'Germania', 703);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70305, 'Cairo', 703);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70306, 'Alegria', 703);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70401, 'Bratsi', 704);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70402, 'Sixaola', 704);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70403, 'Cahuita', 704);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70404, 'Telire', 704);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70501, 'Matina', 705);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70502, 'Battan', 705);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70503, 'Carrandi', 705);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70601, 'Guácimo', 706);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70602, 'Mercedes', 706);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70603, 'Pocora', 706);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70604, 'Río Jiménez', 706);");
        db.execSQL("INSERT INTO Districts (DistrictId, DistrictName, CantonId) VALUES (70605, 'Duacari', 706);");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (1, 1, 1, 'Flexión', 'IE = 0      Viga plana  Sección de apoyo  Sin cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (2, 1, 2, 'Flexión', 'IE = 0      Viga plana  Sección de vano  Sin cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (3, 1, 3, 'Flexión', 'IE = 1      Viga de canto o vigueta  Sección de apoyo  Sin cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (4, 1, 4, 'Flexión', 'IE = 2      Viga de canto o vigueta  Sección de vano  Sin cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (5, 2, 1, 'Flexión', 'IE = 2      Viga plana  Sección de apoyo  Alta densidad de cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (6, 2, 2, 'Flexión', 'IE = 3      Viga plana  Sección de vano  Alta densidad de cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (7, 2, 3, 'Flexión', 'IE = 3      Viga de canto o vigueta  Sección de apoyo  Alta densidad de cercos', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (8, 2, 4, 'Flexión', 'IE = 4      Viga de canto o vigueta  Sección de vano  Alta densidad de cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (9, 3, 1, 'Flexión', 'IE = 3      Viga plana  Sección de apoyo  Baja densidad de cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (10, 3, 2, 'Flexión', 'IE = 4      Viga plana  Sección de vano  Baja densidad de cercos ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (11, 3, 3, 'Flexión', 'IE = 4      Viga de canto o vigueta  Sección de apoyo  Baja densidad de cercos', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (12, 3, 4, 'Flexión', 'IE = 4      Viga de canto o vigueta  Sección de vano  Baja densidad de cercos', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (13, 1, 1, 'Flexocompresión', 'IE = 1      Alta densidad cercos.  Baja cuantía longitudinal.  Dim mín. > 400 mm ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (14, 1, 2, 'Flexocompresión', 'IE = 2      Alta densidad cercos.  Alta cuantía longitudinal.  Dim mín. > 400 mm ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (15, 1, 3, 'Flexocompresión', 'IE = 3      Alta densidad cercos.  Baja cuantía longitudinal.  Dim mín. <= 400 mm', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (16, 1, 4, 'Flexocompresión', 'IE = 4      Alta densidad cercos.  Alta cuantía longitudinal.  Dim mín. <= 400 mm', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (17, 2, 1, 'Flexocompresión', 'IE = 2      Baja densidad cercos.  Baja cuantía longitudinal.  Dim mín. > 400 mm ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (18, 2, 2, 'Flexocompresión', 'IE = 3      Baja densidad cercos.  Alta cuantía longitudinal.  Dim mín. > 400 mm ', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (19, 2, 3, 'Flexocompresión', 'IE = 4      Baja densidad cercos.  Baja cuantía longitudinal.  Dim mín. <= 400 mm', '1');");
        db.execSQL("INSERT INTO ESInformation (ESInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (20, 2, 4, 'Flexocompresión', 'IE = 4      Baja densidad cercos.  Alta cuantía longitudinal.  Dim mín. <= 400 mm', '1');");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (1, 1, 'Clase: X0,	Hormigón en masa, todos los ambientes.	IAA: 0', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (2, 2, 'Clase: XC1,	Seco o permanente húmedo.	IAA: 1', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (3, 3, 'Clase: XC2,	Húmedo, raramente seco.	IAA: 1', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (4, 4, 'Clase: XC3,	Humedad moderada.	IAA: 2', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (5, 5, 'Clase: XC4,	Ciclos húmedos y secos.	IAA: 3', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (6, 6, 'Clase: XD1,	Moderamente húmedo.	IAA: 2', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (7, 7, 'Clase: XD2,	Húmedo, raramente seco.	IAA: 3', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (8, 8, 'Clase: XD3,	Ciclos húmedos y secos.	IAA: 4', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (9, 9, 'Clase: XS1,	Exposición a la acción de la sal, pero no en contacto con el agua de mar .	IAA: 2', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (10, 10, 'Clase: XS2,	Permanentemente sumergidas.	IAA: 3', 1);");
        db.execSQL("INSERT INTO IAAInformation (IAAInformationId, 'Row', Description, Enabled) VALUES (11, 11, 'Clase: XS3,	Zonas expuestas a la acción de la marea o salpicaduras.	IAA: 4', 1);");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (1, 1, 1, 'Flexión', 'Índice de armado longitudinal     Nivel = 1      Dia >= 20mm  Alta cuantía	IE = 1', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (2, 1, 2, 'Flexión', 'Índice de armado longitudinal     Nivel = 2      Dia >= 20mm  Baja cuantía	IE = 2', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (3, 1, 3, 'Flexión', 'Índice de armado longitudinal     Nivel = 2      Dia < 20mm  Alta cuantía	IE = 2', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (4, 1, 4, 'Flexión', 'Índice de armado longitudinal     Nivel = 3      Dia < 20mm  Baja cuantía	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (5, 2, 1, 'Flexión', 'Índice de armado longitudinal     Nivel = 2      Dia >= 20mm  Alta cuantía	IE = 2', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (6, 2, 2, 'Flexión', 'Índice de armado longitudinal     Nivel = 3      Dia >= 20mm  Alta cuantía	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (7, 2, 3, 'Flexión', 'Índice de armado longitudinal     Nivel = 3      Dia >= 20mm  Alta cuantía	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (8, 2, 4, 'Flexión', 'Índice de armado longitudinal     Nivel = 4      Dia >= 20mm  Alta cuantía	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (9, 3, 1, 'Flexión', 'Índice de armado longitudinal     Nivel = 3      Dia >= 20mm  Alta cuantía	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (10, 3, 2, 'Flexión', 'Índice de armado longitudinal     Nivel = 4      Dia >= 20mm  Alta cuantía	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (11, 3, 3, 'Flexión', 'Índice de armado longitudinal     Nivel = 4      Dia >= 20mm  Alta cuantía	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (12, 3, 4, 'Flexión', 'Índice de armado longitudinal     Nivel = 4      Dia >= 20mm  Alta cuantía	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (13, 1, 1, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 1	n >= 0.75  Esp > 5 dia	IE = 1', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (14, 1, 2, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 1	n >= 0.75  Esp < 5 dia	IE = 1', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (15, 1, 3, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 2	n < 0.75  Esp > 5 dia	IE = 2', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (16, 1, 4, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 3	n < 0.75  Esp < 5 dia	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (17, 2, 1, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 2	n >= 0.75  Esp > 5 dia	IE = 2', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (18, 2, 2, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 2	n >= 0.75  Esp < 5 dia	IE = 2', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (19, 2, 3, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 3	n < 0.75  Esp > 5 dia	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (20, 2, 4, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 4	n < 0.75  Esp < 5 dia	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (21, 3, 1, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 3	n >= 0.75  Esp > 5 dia	IE = 3', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (22, 3, 2, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 4	n >= 0.75  Esp < 5 dia	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (23, 3, 3, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 4	n < 0.75  Esp > 5 dia	IE = 4', '1');");
        db.execSQL("INSERT INTO IALInformation (IALInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (24, 3, 4, 'Flexocompresión', 'Índice de armado longitudinal	Nivel = 4	n < 0.75  Esp < 5 dia	IE = 4', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (1, 1, 1, 'Flexión', 'Índice armado transversal     Nivel = 1      Dia > 8 mm  st <= 0.5d ', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (2, 1, 2, 'Flexión', 'Índice armado transversal     Nivel = 1      Dia > 8 mm  st > d ', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (3, 1, 3, 'Flexión', 'Índice armado transversal     Nivel = 2      Dia > 8 mm  st > 0.5d ', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (4, 2, 1, 'Flexión', 'Índice armado transversal     Nivel = 2      Dia <= 8 mm  st <= 0.5d', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (5, 2, 2, 'Flexión', 'Índice armado transversal     Nivel = 2      Dia <= 8 mm  st > d ', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (6, 2, 3, 'Flexión', 'Índice armado transversal     Nivel = 3      Dia <= 8 mm  st > 0.5d', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (7, 1, 1, 'Flexocompresión', 'Índice armado transversal     Nivel = 1      Dia > 8 mm  L <= 10', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (8, 1, 2, 'Flexocompresión', 'Índice armado transversal     Nivel = 2      Dia > 8 mm  10 < L', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (9, 2, 1, 'Flexocompresión', 'Índice armado transversal     Nivel = 2      Dia <= 8 mm  L <= 10', '1');");
        db.execSQL("INSERT INTO IATInformation (IATInformationId, 'Row', Col, ElementType, Description, Enabled) VALUES (10, 2, 2, 'Flexocompresión', 'Índice armado transversal     Nivel = 3      Dia <= 8 mm  10 < L', '1');");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (1, 1, 1, 'Leve', 'IDE = D	Despreciable Consecuencia fallo: Leve Urgencia de intervención: > 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (2, 1, 1, 'Importante', 'IDE = D	Despreciable Consecuencia fallo: Importante Urgencia de intervención: > 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (3, 1, 2, 'Leve', 'IDE = D	Despreciable Consecuencia fallo: Leve Urgencia de intervención: > 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (4, 1, 2, 'Importante', 'IDE = D	Despreciable Consecuencia fallo: Importante Urgencia de intervención: > 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (5, 1, 3, 'Leve', 'IDE = D	Despreciable Consecuencia fallo: Leve Urgencia de intervención: > 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (6, 1, 3, 'Importante', 'IDE = M	Medio Consecuencia fallo: Importante Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (7, 1, 4, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (8, 1, 4, 'Importante', 'IDE = M	Medio Consecuencia fallo: Importante Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (9, 2, 1, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (10, 2, 1, 'Importante', 'IDE = M	Medio Consecuencia fallo: Importante Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (11, 2, 2, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (12, 2, 2, 'Importante', 'IDE = M	Medio Consecuencia fallo: Importante Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (13, 2, 3, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (14, 2, 3, 'Importante', 'IDE = S	Severo Consecuencia fallo: Importante Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (15, 2, 4, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (16, 2, 4, 'Importante', 'IDE = S	Severo Consecuencia fallo: Importante Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (17, 3, 1, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (18, 3, 1, 'Importante', 'IDE = S	Severo Consecuencia fallo: Importante Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (19, 3, 2, 'Leve', 'IDE = M	Medio Consecuencia fallo: Leve Urgencia de intervención: 5 - 10 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (20, 3, 2, 'Importante', 'IDE = S	Severo Consecuencia fallo: Importante Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (21, 3, 3, 'Leve', 'IDE = S	Severo Consecuencia fallo: Leve Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (22, 3, 3, 'Importante', 'IDE = MS	Muy severo Consecuencia fallo: Importante Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (23, 3, 4, 'Leve', 'IDE = S	Severo Consecuencia fallo: Leve Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (24, 3, 4, 'Importante', 'IDE = MS	Muy severo Consecuencia fallo: Importante Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (25, 4, 1, 'Leve', 'IDE = S	Severo Consecuencia fallo: Leve Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (26, 4, 1, 'Importante', 'IDE = MS	Muy severo Consecuencia fallo: Importante Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (27, 4, 2, 'Leve', 'IDE = S	Severo Consecuencia fallo: Leve Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (28, 4, 2, 'Importante', 'IDE = MS	Muy severo Consecuencia fallo: Importante Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (29, 4, 3, 'Leve', 'IDE = S	Severo Consecuencia fallo: Leve Urgencia de intervención: 2 - 5 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (30, 4, 3, 'Importante', 'IDE = MS	Muy severo Consecuencia fallo: Importante Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (31, 4, 4, 'Leve', 'IDE = MS	Muy severo Consecuencia fallo: Leve Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IDEInformation (IDEInformationId, 'Row', Col, failureConsequence, Description, Enabled) VALUES (32, 4, 4, 'Importante', 'IDE = MS	Muy severo Consecuencia fallo: Importante Urgencia de intervención: 0 - 2 años', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (1, 1, 1, 'Profundidad carbonatación   Nivel = 1     Xco2 = 0', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (2, 1, 2, 'Profundidad carbonatación   Nivel = 2     Xco2 < 0', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (3, 1, 3, 'Profundidad carbonatación   Nivel = 3     Xco2 = c', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (4, 1, 4, 'Profundidad carbonatación   Nivel = 4     Xco2 > c', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (5, 2, 1, 'Nivel de cloruros	Nivel = 1	Xcl = 0', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (6, 2, 2, 'Nivel de cloruros	Nivel = 2	Xcl < 0', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (7, 2, 3, 'Nivel de cloruros	Nivel = 3	Xcl = 0', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (8, 2, 4, 'Nivel de cloruros	Nivel = 4	Xcl > c', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (9, 3, 1, 'Fisuración por corrosión	Nivel = 1	Sin fisuras', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (10, 3, 2, 'Fisuración por corrosión	Nivel = 2	Fisuras < 0.3mm', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (11, 3, 3, 'Fisuración por corrosión	Nivel = 3	Fisuras > 0.3mm', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (12, 3, 4, 'Fisuración por corrosión	Nivel = 4	Fisuración generalizada', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (13, 4, 1, 'Resistividad	Nivel = 1	> 1000', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (14, 4, 2, 'Resistividad	Nivel = 2	500 - 1000', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (15, 4, 3, 'Resistividad	Nivel = 3	100 - 500', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (16, 4, 4, 'Resistividad	Nivel = 4	< 100', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (17, 5, 1, 'Pérdida sección	Nivel = 1	< 1%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (18, 5, 2, 'Pérdida sección	Nivel = 2	1 - 5%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (19, 5, 3, 'Pérdida sección	Nivel = 3	5 - 10%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (20, 5, 4, 'Pérdida sección	Nivel = 4	> 10%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (21, 6, 1, 'Intensidad de corrosión	Nivel = 1	< 0.1%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (22, 6, 2, 'Intensidad de corrosión	Nivel = 2	0.1 - 0.5%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (23, 6, 3, 'Intensidad de corrosión	Nivel = 3	0.5 - 1%', 1);");
        db.execSQL("INSERT INTO IndicatorNames (IndicatorNameId, 'Row', Col, Description, Enabled) VALUES (24, 6, 4, 'Intensidad de corrosión	Nivel = 4	> 1%', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (1, 'San José', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (2, 'Alajuela', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (3, 'Cartago', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (4, 'Heredia', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (5, 'Guanacaste', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (6, 'Puntarenas', 1);");
        db.execSQL("INSERT INTO Provinces (ProvinceId, ProvinceName, CountryId) VALUES (7, 'Limón', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (1, 'Edificación', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (2, 'Puente', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (3, 'Muelle', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (4, 'Muro de contención', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (5, 'Tanque de almacenemiento', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (6, 'Plataforma petrolera', 1);");
        db.execSQL("INSERT INTO StructureTypes (StructureTypeId, Name, Enabled) VALUES (7, 'Otro', 1);");
        db.execSQL("INSERT INTO Users (UserId, Name, Lastname, Email, LoginDate, Enabled) VALUES (1, 'Bryan', 'Alfaro Porras', 'bryanalfarop@gmail.com', '2017-01-09', 1);");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
